# A deployment template for building and providing artifacts on tag releases
name: Deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Build the mod
        run: ./gradlew --no-daemon build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Neonium
          path: build/libs
